version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
   configuration: docs/source/conf.py

conda:
  environment: docs/environment.yml

python:
   install:
   - requirements: requirements.txt
