version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements-doc.txt
    - requirements: requirements.txt
