import logging
import pandas as pd
import plotly.express as px
import report_creator as rc

logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    # Load data
    try:
        df = pd.read_csv("examples/logs.csv")
    except FileNotFoundError:
        print("Error: examples/logs.csv not found.")
        exit(1)

    # Data Preprocessing
    # Remove potential double quoting artifacts if pandas didn't handle them automatically in a way we want
    # Note: read_csv usually handles quotes, but if the CSV has triple quotes pandas might interpret them literal if quotechar is not set correctly or if the file is weird.
    # Based on file inspection, it seems okay, but let's be safe with stripping just in case.
    for col in ['request', 'referer', 'user_agent']:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip('"')

    # Parse Time
    # Format in logs.csv: 18/Jul/2011 03:35:52
    df['dt'] = pd.to_datetime(df['time'], format='%d/%b/%Y %H:%M:%S', errors='coerce')
    df = df.dropna(subset=['dt']) # Drop rows where time couldn't be parsed

    # Extract Path from Request (e.g., "GET /robots.txt HTTP/1.1" -> "/robots.txt")
    def extract_path(req):
        try:
            parts = req.split()
            if len(parts) >= 2:
                return parts[1]
        except Exception:
            pass
        return req

    df['path'] = df['request'].apply(extract_path)

    # Metrics Calculations
    total_requests = len(df)
    unique_visitors = df['ip'].nunique()
    # Size is in bytes.
    total_bandwidth_mb = df['size'].sum() / (1024 * 1024)

    error_requests = df[df['status'] >= 400]
    error_rate = (len(error_requests) / total_requests) * 100 if total_requests > 0 else 0

    # Visualizations

    # 1. Requests over time (Hourly)
    requests_over_time = df.set_index('dt').resample('h').size().reset_index(name='count')
    fig_time = px.line(requests_over_time, x='dt', y='count', title='Hourly Traffic', markers=True)
    fig_time.update_layout(xaxis_title="Time", yaxis_title="Number of Requests")

    # 2. Status Codes Distribution
    status_counts = df['status'].value_counts().reset_index()
    status_counts.columns = ['status', 'count']
    fig_status = px.pie(status_counts, values='count', names='status', title='Status Code Distribution')

    # 3. Top 10 User Agents
    top_ua = df['user_agent'].value_counts().head(10).reset_index()
    top_ua.columns = ['user_agent', 'count']
    # Truncate long UA strings for display
    top_ua['user_agent_short'] = top_ua['user_agent'].str.slice(0, 50) + "..."
    fig_ua = px.bar(top_ua, x='count', y='user_agent_short', orientation='h', title='Top 10 User Agents', hover_data=['user_agent'])
    fig_ua.update_layout(yaxis={'categoryorder':'total ascending'})

    # 4. Top 10 Paths
    top_paths = df['path'].value_counts().head(10).reset_index()
    top_paths.columns = ['path', 'count']
    fig_paths = px.bar(top_paths, x='path', y='count', title='Top 10 Requested Paths')

    # Build Report
    with rc.ReportCreator(
        title="Web Server Log Infographic",
        description="Analysis of web server traffic patterns from `examples/logs.csv`",
        footer="Generated by Report Creator"
    ) as report:
        view = rc.Block(
            rc.Group(
                rc.Metric(heading="Total Requests", value=total_requests),
                rc.Metric(heading="Unique Visitors", value=unique_visitors),
                rc.Metric(heading="Total Bandwidth", value=f"{total_bandwidth_mb:.2f} MB"),
                rc.Metric(heading="Error Rate", value=f"{error_rate:.2f}%"),
                label="Key Performance Indicators"
            ),
            rc.Separator(),
            rc.Widget(fig_time, label="Traffic Trends"),
            rc.Group(
                rc.Widget(fig_status, label="Status Codes"),
                rc.Widget(fig_paths, label="Top Content"),
            ),
            rc.Widget(fig_ua, label="User Agents"),
            rc.Separator(),
            rc.EventMetric(
                df,
                heading="Traffic Volume",
                date="dt",
                frequency="D", # Daily
                condition="status == 200", # Count successful requests
                label="Successful Request Volume (Daily)"
            )
        )

        output_file = "logs_infographic.html"
        report.save(view, output_file, prettify_html=False)
        print(f"Report saved to {output_file}")
