name: docs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip:
      - sphinx
      - sphinx_copybutton
      - sphinx_rtd_theme
      - sphinx-autodoc-typehints
      - sphinxcontrib-bibtex
      - nbsphinx
      - recommonmark
      - sphinx-markdown-tables
