name: docs

dependencies:
  - python=3.11
  - pip
  - pip:
      - sphinx
      - sphinx-readable-theme
      - sphinx_copybutton
      - sphinx-autodoc-typehints
      - sphinxcontrib-bibtex
      - nbsphinx
      - recommonmark
      - sphinx-markdown-tables
      - sphinxcontrib-mermaid
      - sphinx-book-theme
