name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: docs/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python setup.py install
      - name: pushing to gh-pages
        shell: bash -l {0}
        run: |
          cd docs && make html
      - name: pushing to gh-pages
        shell: bash
        run: |
          echo ::group::Create README for gh-pages
          SHA=$GITHUB_SHA
          echo "$SHA $GITHUB_EVENT_NAME"
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            SHA=$(cat "$GITHUB_EVENT_PATH" | jq -r .pull_request.head.sha)
          fi
          DIR_HTML="docs/build/html/"
          echo "#GitHub Pages" > "$DIR_HTML/README.md"
          echo "" >> "$DIR_HTML/README.md"
          echo "Last update of sphinx html documentation from [$SHORT_SHA](https://github.com/$GITHUB_REPOSITORY/tree/$SHA)" >> "$DIR_HTML/README.md"
          cat "$DIR_HTML/README.md"
          echo ::endgroup::
          echo ::group::Create .nojekyll in case 'sphinx.ext.githubpages' is not used
          touch "$DIR_HTML"/.nojekyll
          echo ::endgroup::
          echo ::group::Push to gh-pages
          git add -f "$DIR_HTML"
          git commit -m "From $GITHUB_REF $SHA"
          git push origin `git subtree split --prefix "$DIR_HTML" "main"`:gh-pages --force
          echo ::endgroup::
